// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/7de6c3dd94feaeb21f20054b9f30d5dabc5efabd/path-to-regexp/path-to-regexp.d.ts
declare module "path-to-regexp" {

    function pathToRegexp(path: string, keys?: string[], options?: pathToRegexp.Options): RegExp;

    namespace pathToRegexp {

        interface Options {
            sensitive?: boolean;
            strict?: boolean;
            end?: boolean;
        }

    }

    export = pathToRegexp;

}
